## 0. Definición de funciones

In [8]:
def multiplicar(x,y):
    return x * y

In [9]:
x=2
y=3
print(multiplicar(x,y))

6


## 1. Creación de arrays

#### 1.1. Valores iguales

In [ ]:
import numpy as np

In [ ]:
# Array cuyos valores son todos 0
a=np.zeros((2, 3, 4))
print("Array con zeros:\n", a)
print("Forma del array:", a.shape)
print("-------------------------------------")
# Array cuyos valores son todos 1
b= np.ones((2, 3, 4))
print("Array con unos:\n", b)
print("Forma del array:", b.shape)
print("-------------------------------------")
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
c=np.full((2, 3, 4), 8)
print("Array con ochos:\n", c)
print("Forma del array:", c.shape)

Array con zeros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Forma del array: (2, 3, 4)
-------------------------------------
Array con unos:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Forma del array: (2, 3, 4)
-------------------------------------
Array con unos:
 [[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]
Forma del array: (2, 3, 4)


#### 1.2. Valores diferentes

In [7]:
#Manual
d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array manualmente definido:\n", d)
print("-------------------------------------")
#Array por rangos
e = np.arange(1, 10, 2)
print("Array por rangos:\n", e)
print("-------------------------------------")
#Array aleatorio
f = np.random.rand(2, 3)
print("Array aleatorio:\n", f)
print("-------------------------------------")
#Array aleatorio conforme a una distribución normal
g = np.random.randn(2, 3)
print("Array aleatorio conforme a una distribución normal:\n", g)
print("-------------------------------------")

Array manualmente definido:
 [[1 2 3]
 [4 5 6]]
-------------------------------------
Array por rangos:
 [1 3 5 7 9]
-------------------------------------
Array aleatorio:
 [[0.36616871 0.06925998 0.65162696]
 [0.36785156 0.54253041 0.3003272 ]]
-------------------------------------
Array aleatorio conforme a una distribución normal:
 [[ 0.50207122 -1.06685141 -0.72092755]
 [-0.19482441 -1.34269898 -0.39669015]]
-------------------------------------


## 2. Acceso a los elementos de un array

#### 2.1. Array unidimensional

In [14]:
# Creación de un Array unidimensional
array_uni = np.array([1, 3, 5, 7, 9, 11])
print("Array_uni:", array_uni)
print("Shape:", array_uni.shape)
print("----------------------------------------")
print("- Seleccionamos segundo elemento:", array_uni[1])
print("- Seleccionamos el cuarto y quinto:\n", array_uni[2:4])
print("- Seleccionamos los elementos 1, 5 y 9:\n", array_uni[0::2])


Array_uni: [ 1  3  5  7  9 11]
Shape: (6,)
----------------------------------------
- Seleccionamos segundo elemento: 3
- Seleccionamos el cuarto y quinto:
 [5 7]
- Seleccionamos los elementos 1, 5 y 9:
 [1 5 9]


#### 2.2. Array multidimensional

In [ ]:
# Creación de un Array multidimensional
array_multi = np.array([[1, 3, 5], [7, 9, 11]])
print("Array_multi:", array_multi)
print("Shape:", array_multi.shape)
print("----------------------------------------")
print("- Seleccionamos el segundo elemento de la primera fila:", array_multi[0, 1])
print("- Seleccionamos la segunda fila:", array_multi[1, :])
print("- Seleccionamos los dos primeros elemento de cada fila:\n", array_multi[0:2, 0:2])

Array_multi: [[ 1  3  5]
 [ 7  9 11]]
Shape: (2, 3)
----------------------------------------
- Seleccionamos el segundo elemento de la primera fila: 3
- Seleccionamos la segunda fila: [ 7  9 11]
- Seleccionamos los dos primeros elemento de la primera fila:
 [[1 3]
 [7 9]]


## 3. Modificación de un Array

In [86]:
# Creación de un Array unidimensional inicializado con el rango de elementos 0-27
array1 = np.arange(28)
print("Array con 28 elementos empezando por 0:", array1)
print("Shape:", array1.shape)
print("----------------------------------------")
print("- Añadimos más columnas al array:\n",array1.reshape(7, 4)) #En otro array, para hacerlo en el mismo: array1.shape=(7,4)
print("- Nuevo shape:", array1.reshape(7, 4).shape)
print("----------------------------------------")
print("- Lo volvemos unidimensional:\n", array1.flatten())
print("- Nuevo shape:", array1.flatten().shape)
print("----------------------------------------")
print("- Ponemos valores mayores que 5 como 1 y el resto, 0:\n", np.where(array1>5, 1, 0))

Array con 28 elementos empezando por 0: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
Shape: (28,)
----------------------------------------
- Añadimos más columnas al array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
- Nuevo shape: (7, 4)
----------------------------------------
- Lo volvemos unidimensional:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
- Nuevo shape: (28,)
----------------------------------------
- Ponemos valores mayores que 5 como 1 y el resto, 0:
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 4. Operaciones aritméticas con Arrays

### 4.1. Vectores

In [35]:
array1 = np.arange(2, 18, 2)
array2=np.random.rand(8,1)
print("Array 1:", array1)
print("Shape:", array1.shape)
print("Array 2:", array2)
print("Shape:", array2.shape)
# Suma
print(f"Suma: {array1 + 3}")
# Resta
print(f"Resta: {array1 - 4}")
# Multiplicacion de vectores
print(f"Multiplicacion de vectores: {np.dot(array1, array2)}")

Array 1: [ 2  4  6  8 10 12 14 16]
Shape: (8,)
Array 2: [[0.70149734]
 [0.14983162]
 [0.36752804]
 [0.59769564]
 [0.2316658 ]
 [0.6217155 ]
 [0.96845706]
 [0.05070426]]
Shape: (8, 1)
Suma: [ 5  7  9 11 13 15 17 19]
Resta: [-2  0  2  4  6  8 10 12]
Multiplicacion de vectores: [33.1359655]


In [ ]:
#Producto vectorial: vector ortogonal de cada matriz
vector1=np.arange(5,20,5)
vector2=np.array([3,5,2])
np.cross(vector1,vector2)

array([-55,  35,  -5])

### 4.2. Matrices

In [39]:
#matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
matriz1=np.random.rand(3,2)
matriz2=np.random.rand(2,3)
#Multiplicación de matrices
print(f"Multiplicación: {np.matmul(matriz1,matriz2)}")


Multiplicación: [[0.63636389 0.76114811 0.69474074]
 [0.10694771 0.19232452 0.21261039]
 [0.77698375 0.73982354 0.56620843]]


In [55]:
from numpy.linalg import inv
from numpy.linalg import det
matriz3=np.array([[3,2,9],[7,5,1],[2,8,3]])
print(f"Matriz 1: {matriz3}")
print(f"Traspuesta: {matriz3.transpose()}")
print(f"Determinante: {det(matriz3)}")
print(f"Inversa: {inv(matriz3)}")
print(f"Comprobacion propiedad: {np.matmul(matriz3, inv(matriz3))}")

Matriz 1: [[3 2 9]
 [7 5 1]
 [2 8 3]]
Traspuesta: [[3 7 2]
 [2 5 8]
 [9 1 3]]
Determinante: 397.0000000000001
Inversa: [[ 0.01763224  0.16624685 -0.10831234]
 [-0.04785894 -0.02267003  0.1511335 ]
 [ 0.11586902 -0.05037783  0.00251889]]
Comprobacion propiedad: [[ 1.00000000e+00 -3.46944695e-17  3.46944695e-18]
 [ 1.38777878e-17  1.00000000e+00  8.67361738e-17]
 [-4.16333634e-17  6.93889390e-18  1.00000000e+00]]


## Funciones estadísticas sobre Arrays

In [84]:
matriz4=np.random.rand(3,4)
print("Matriz: ", matriz4)
print("Shape", matriz4.shape)
print(f" Mínimo: {matriz4.min()}")
print(f" Máximo: {matriz4.max()}")
print("Suma de los elementos: ", matriz4.sum())
print(f"Suma por filas: {matriz4.sum(axis=0)}")
print(f"Suma por columnas: {matriz4.sum(axis=1)}")
print("Media: ", matriz4.mean())
print("Mediana: ", np.median(matriz4))
print("Desv. Est.: ", matriz4.std())
print(f"Producto de todos los numeros: {np.prod(matriz4)}")
print(f"Porducto de cada elemento de la fila 1 y 2: {np.multiply(matriz4[0], matriz4[1])}")
print(f"Suma acumulada: {matriz4.cumsum()}")
print(f"Producto acumulado: {matriz4.cumprod()}")

Matriz:  [[0.95868577 0.49818247 0.16362353 0.97663091]
 [0.72519044 0.71072009 0.34762    0.6922952 ]
 [0.5567866  0.58611069 0.68355671 0.66173858]]
Shape (3, 4)
 Mínimo: 0.16362353497212123
 Máximo: 0.9766309126908234
Suma de los elementos:  7.5611409962864515
Suma por filas: [2.24066281 1.79501325 1.19480025 2.33066469]
Suma por columnas: [2.59712268 2.47582574 2.48819258]
Media:  0.630095083023871
Mediana:  0.6726476452985793
Desv. Est.:  0.21859939105891582
Producto de todos los numeros: 0.00139738835609985
Porducto de cada elemento de la fila 1 y 2: [0.69522975 0.35406829 0.05687881 0.6761169 ]
Suma acumulada: [0.95868577 1.45686823 1.62049177 2.59712268 3.32231312 4.03303321
 4.38065321 5.07294841 5.62973501 6.21584571 6.89940242 7.561141  ]
Producto acumulado: [0.95868577 0.47760044 0.07814667 0.07632046 0.05534686 0.03933613
 0.01367403 0.00946646 0.0052708  0.00308927 0.00211169 0.00139739]


In [ ]:
# Funciones universales eficientes proporcionadas por numpy: **ufunc**
number=6
print("Cuadrado: ", np.square(number))
print("Raíz cuadrada: ", np.sqrt(number))
print("Valor exponencial: ", np.exp(number))
print("Logaritmo natural: ", np.log(number))
print("Numero phi: ", np.pi)
print("Coseno: ", np.cos(number))
print("Seno: ", np.sin(number))

Cuadrado de los elementos:  [  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169. 196.
 225. 256. 289. 324. 361. 400.]
Raíz cuadrada de los elementos:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595]
Valor exponencial de los elementos:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08 4.85165195e+08]
Logaritmo natural de los elementos:  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898 2.99573227]


In [25]:
dir(array1) #Devuelve una lista de los atributos y métodos definidos para ese objeto

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
