## 0. Definición de funciones

In [8]:
def multiplicar(x,y):
    return x * y

In [9]:
x=2
y=3
print(multiplicar(x,y))

6


## 1. Creación de arrays

#### 1.1. Valores iguales

In [ ]:
import numpy as np

In [ ]:
# Array cuyos valores son todos 0
a=np.zeros((2, 3, 4))
print("Array con zeros:\n", a)
print("Forma del array:", a.shape)
print("-------------------------------------")
# Array cuyos valores son todos 1
b= np.ones((2, 3, 4))
print("Array con unos:\n", b)
print("Forma del array:", b.shape)
print("-------------------------------------")
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
c=np.full((2, 3, 4), 8)
print("Array con ochos:\n", c)
print("Forma del array:", c.shape)

Array con zeros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Forma del array: (2, 3, 4)
-------------------------------------
Array con unos:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Forma del array: (2, 3, 4)
-------------------------------------
Array con unos:
 [[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]
Forma del array: (2, 3, 4)


#### 1.2. Valores diferentes

In [7]:
#Manual
d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array manualmente definido:\n", d)
print("-------------------------------------")
#Array por rangos
e = np.arange(1, 10, 2)
print("Array por rangos:\n", e)
print("-------------------------------------")
#Array aleatorio
f = np.random.rand(2, 3)
print("Array aleatorio:\n", f)
print("-------------------------------------")
#Array aleatorio conforme a una distribución normal
g = np.random.randn(2, 3)
print("Array aleatorio conforme a una distribución normal:\n", g)
print("-------------------------------------")

Array manualmente definido:
 [[1 2 3]
 [4 5 6]]
-------------------------------------
Array por rangos:
 [1 3 5 7 9]
-------------------------------------
Array aleatorio:
 [[0.36616871 0.06925998 0.65162696]
 [0.36785156 0.54253041 0.3003272 ]]
-------------------------------------
Array aleatorio conforme a una distribución normal:
 [[ 0.50207122 -1.06685141 -0.72092755]
 [-0.19482441 -1.34269898 -0.39669015]]
-------------------------------------


## 2. Acceso a los elementos de un array

#### 2.1. Array unidimensional

In [14]:
# Creación de un Array unidimensional
array_uni = np.array([1, 3, 5, 7, 9, 11])
print("Array_uni:", array_uni)
print("Shape:", array_uni.shape)
print("----------------------------------------")
print("- Seleccionamos segundo elemento:", array_uni[1])
print("- Seleccionamos el cuarto y quinto:\n", array_uni[2:4])
print("- Seleccionamos los elementos 1, 5 y 9:\n", array_uni[0::2])


Array_uni: [ 1  3  5  7  9 11]
Shape: (6,)
----------------------------------------
- Seleccionamos segundo elemento: 3
- Seleccionamos el cuarto y quinto:
 [5 7]
- Seleccionamos los elementos 1, 5 y 9:
 [1 5 9]


#### 2.2. Array multidimensional

In [ ]:
# Creación de un Array multidimensional
array_multi = np.array([[1, 3, 5], [7, 9, 11]])
print("Array_multi:", array_multi)
print("Shape:", array_multi.shape)
print("----------------------------------------")
print("- Seleccionamos el segundo elemento de la primera fila:", array_multi[0, 1])
print("- Seleccionamos la segunda fila:", array_multi[1, :])
print("- Seleccionamos los dos primeros elemento de cada fila:\n", array_multi[0:2, 0:2])

Array_multi: [[ 1  3  5]
 [ 7  9 11]]
Shape: (2, 3)
----------------------------------------
- Seleccionamos el segundo elemento de la primera fila: 3
- Seleccionamos la segunda fila: [ 7  9 11]
- Seleccionamos los dos primeros elemento de la primera fila:
 [[1 3]
 [7 9]]


## 3. Modificación de un Array

In [ ]:
# Creación de un Array unidimensional inicializado con el rango de elementos 0-27
array1 = np.arange(28)
print("Array con 28 elementos empezando por 0:", array1)
print("Shape:", array1.shape)
print("----------------------------------------")
array2=array1.reshape(7, 4)
print("- Añadimos más columnas al array:\n",array2) #En otro array, para hacerlo en el mismo: array1.shape=(7,4)
print("- Nuevo shape:", array2.shape)
print("----------------------------------------")
print("----------------------------------------")
array2=array1.reshape(7, 4)
print("- Lo volvemos unidimensional:\n",array2.ravel()) #En otro array, para hacerlo en el mismo: array1.shape=(7,4)

Array con 28 elementos empezando por 0: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
Shape: (28,)
----------------------------------------
- Añadimos más columnas al array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
- Nuevo shape: (7, 4)
----------------------------------------
----------------------------------------
- Lo volvemos unidimensional:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
- Nuevo shape: (7, 4)


## 4. Operaciones aritméticas con Arrays

In [24]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(2, 18, 2)
array2 = np.array([3])
print("Array 1:", array1)
print("Shape:", array1.shape)
print("Array 2:", array2)
print("Shape:", array2.shape)
# Suma
print(array1 + array2)
# Resta
print(array1 - array2)

Array 1: [ 2  4  6  8 10 12 14 16]
Shape: (8,)
Array 2: [3]
Shape: (1,)
[ 5  7  9 11 13 15 17 19]
[-1  1  3  5  7  9 11 13]


In [36]:
# Multiplicacion
# Importante: No es una multiplicación de matrices
print(array1 * array2)

[  0   4  12  24  40  60  84 112]


## Funciones estadísticas sobre Arrays

In [ ]:
array1=np.linspace(1,20,20)
print("Array 1: ", array1)
print("Suma de los elementos: ", array1.sum())
print("Media: ", array1.mean())

Array 1: [ 1  3  5  7  9 11 13 15 17 19]


In [25]:
dir(array1) #Devuelve una lista de los atributos y métodos definidos para ese objeto

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [ ]:
#Ayuda sobre .mean()
print(pydoc.render_doc(np.mean))

Python Library Documentation: _ArrayFunctionDispatcher in module numpy

mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>
)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in comput

Funciones universales eficientes proporcionadas por numpy: **ufunc**

In [ ]:
# Funciones universales eficientes proporcionadas por numpy: **ufunc**
print("Cuadrado de los elementos: ", np.square(array1))
print("Raíz cuadrada de los elementos: ", np.sqrt(array1))
print("Valor exponencial de los elementos: ", np.exp(array1))
print("Logaritmo natural de los elementos: ", np.log(array1))