## 1. Creación de tensores

In [ ]:
print(torch.zeros(2)) #Torch de zeros
print(torch.ones(2)) #Torch de unos
print(torch.linspace(1,10,10)) #Torch de 1 a 10 en 10 pasos

tensor([0., 0.])
tensor([1., 1.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [12]:
import numpy as np

lista=[1,2,3,4,5,6,7,8,9]
print(lista)
print(f"Tensor desde una lista: {torch.Tensor(lista)}")
print("-------------------------------------------------------")
array=np.random.rand(9)
print(array)
print(f"Tensor desde una lista: {torch.from_numpy(array)}")

[1, 2, 3, 4, 5, 6, 7, 8, 9]
Tensor desde una lista: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
-------------------------------------------------------
[0.08793497 0.93590818 0.8674491  0.40766098 0.27487743 0.74836067
 0.14478591 0.20944597 0.68025092]
Tensor desde una lista: tensor([0.0879, 0.9359, 0.8674, 0.4077, 0.2749, 0.7484, 0.1448, 0.2094, 0.6803],
       dtype=torch.float64)


In [13]:
# Desde torch a numpy
x=torch.rand(1)

x.numpy()

array([0.6375519], dtype=float32)

## 2. Atributos