## 1. Creación de tensores

In [ ]:
print(torch.zeros(2)) #Torch de zeros
print(torch.ones(2)) #Torch de unos
print(torch.linspace(1,10,10)) #Torch de 1 a 10 en 10 pasos

tensor([0., 0.])
tensor([1., 1.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [12]:
import numpy as np

lista=[1,2,3,4,5,6,7,8,9]
print(lista)
print(f"Tensor desde una lista: {torch.Tensor(lista)}")
print("-------------------------------------------------------")
array=np.random.rand(9)
print(array)
print(f"Tensor desde una lista: {torch.from_numpy(array)}")

[1, 2, 3, 4, 5, 6, 7, 8, 9]
Tensor desde una lista: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
-------------------------------------------------------
[0.08793497 0.93590818 0.8674491  0.40766098 0.27487743 0.74836067
 0.14478591 0.20944597 0.68025092]
Tensor desde una lista: tensor([0.0879, 0.9359, 0.8674, 0.4077, 0.2749, 0.7484, 0.1448, 0.2094, 0.6803],
       dtype=torch.float64)


In [13]:
# Desde torch a numpy
x=torch.rand(1)

x.numpy()

array([0.6375519], dtype=float32)

## 2. Atributos

In [2]:
import torch

In [3]:
tensor = torch.rand(5, 2, 3)

In [4]:
tensor.ndim

3

In [5]:
tensor.shape

torch.Size([5, 2, 3])

In [6]:
tensor.dtype

torch.float32

## 3. Manipulación

In [ ]:
tensor = torch.linspace(0, 9, 10)
tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
tensor = tensor. reshape(2, 5)
tensor

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [9]:
tensor.T

tensor([[0., 5.],
        [1., 6.],
        [2., 7.],
        [3., 8.],
        [4., 9.]])

In [10]:
tensor.flatten()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 4. Operaciones

In [12]:
tensor=tensor.flatten()
5+tensor

tensor([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [13]:
tensor-4

tensor([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [14]:
3*tensor

tensor([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [15]:
tensor.pow(2) #Elevar al cuadrado

tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [16]:
tensor.log()

tensor([  -inf, 0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794,
        2.1972])

In [17]:
tensor.exp()

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03])

In [18]:
tensor.cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455, -0.9111])

In [19]:
tensor.sin()

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894,  0.4121])

In [20]:
tensor.min()

tensor(0.)

In [21]:
tensor.max()

tensor(9.)

In [22]:
tensor.mean()

tensor(4.5000)

In [23]:
tensor.median()

tensor(4.)

In [24]:
tensor.var()

tensor(9.1667)

In [25]:
tensor.std()

tensor(3.0277)

## 5. Selección elementos

In [26]:
tensor[0]

tensor(0.)

In [27]:
tensor[0].item()

0.0

In [28]:
int(tensor[0])

0

In [29]:
tensor[1:7:2]

tensor([1., 3., 5.])

## 6. Cálculo del gradiente

In [ ]:
# Definiciones
x=torch.tensor(1.0, requires_grad=True)

y=x**2
y.backward()
x.grad

tensor(2.)

In [37]:
x=torch.linspace(6,30,5, requires_grad=True)

y=5/x
y.backward(torch.ones_like(x)) # Calcula la derivadapor cada valor del vector x
x.grad

tensor([-0.1389, -0.0347, -0.0154, -0.0087, -0.0056])